### ISSUE TITLE
Choose documentation system

### ISSUE THREAD

**Issue by John-S4** [Okazanta/okazanta-legacy#7]
Cachet uses readme.io for documentation. 

We could continue to use readme.io or take this opportunity to change it for something else, like Docusauras.

Open to suggestions and thoughts on both of those or any other options.

**Comment by etec-masterofsynapse** [comment]
Is your target to have an open-source docs system, should it be SaaS or self-hosted?
I can support this project via my company, [Epsilon PS e.K.](epsilon.ps), and can offer hosting and IT expertise, if we would need servers for the docs system, etc.

Is there a Discord server where the discussions are happening?

**Comment by John-S4** [comment]
> Is your target to have an open-source docs system, should it be SaaS or self-hosted?

Those are the big questions. :)

Personally I would prefer it if we were using something open source, but I'm not very familiar with any of the alternatives. Crowdin just seems to be the standard and also has the advantage that all of the existing translations of Cachet would be easy to copy there (and the existing translators are used to it). 

Anyone have any experience with a decent FOSS alternative. 

> Is there a Discord server where the discussions are happening?

There is a Discord server, but I am currently the only member of it. [Discord](https://discord.gg/4CtKuuHrqJ)

**Comment by jacobwoffenden** [comment]
Docusauras to GitHub Pages would be my suggestion

**Comment by John-S4** [comment]
> Docusauras on GitHub Pages would be my suggestion

I'm a big fan of Docusauras and it would normally be my go-to but I'm definitely interested in exploring other options if someone has any.

**Comment by Wild1145** [comment]
Something like Atlassian Confluence might be worth consideration. It's SaaS and Free for 10 users and they tend to be really good with their open source free plans.

**Comment by etec-masterofsynapse** [comment]
> Something like Atlassian Confluence might be worth consideration. It's SaaS and Free for 10 users and they tend to be really good with their open source free plans.

While I agree with your general statement I wouldn't recommend using Confluence as a docs system, for the whole reason that collaborative "anonymous" edits are not possible.
With a solution that is based on a Git repository, anyone can open a pull request and do the edits natively. Also, that way we can base the articles on Markdown, a publicly available formatting language, which will make future migrations easier.
Atlassian uses their proprietary editor.

**Comment by Wild1145** [comment]
> > Something like Atlassian Confluence might be worth consideration. It's SaaS and Free for 10 users and they tend to be really good with their open source free plans.
> 
> While I agree with your general statement I wouldn't recommend using Confluence as a docs system, for the whole reason that collaborative "anonymous" edits are not possible. With a solution that is based on a Git repository, anyone can open a pull request and do the edits natively. Also, that way we can base the articles on Markdown, a publicly available formatting language, which will make future migrations easier. Atlassian uses their proprietary editor.

Equally though "Anonymous" edits aren't possible using anything over Git either (And fwiw it is possible on Confluence, it's just bad practice) as you have to have a Github account and things have to be attributable to that account, no different to Confluence. 

It ultimately depends on who is going to be writing the documentation and how much maintenance you want, Confluence provides everything except the content, and their content editor is trivial to use. Anything we use that is Git based requires the management, skill to actually know how to edit / manage the content as well as the hosting of it. None of which is impossible but it's about deciding what makes the most sense. I'm not against git based documentation, I just think it tends to be a bit rubbish when you want to start doing more complex content.

**Comment by etec-masterofsynapse** [comment]
> Equally though "Anonymous" edits aren't possible using anything over Git either (And fwiw it is possible on Confluence, it's just bad practice) as you have to have a Github account and things have to be attributable to that account, no different to Confluence.

My point with "Anonymous" edits was that a Confluence SaaS instance uses its own user database, so someone wanting to contribute to the documentation would have to create a specific account, just for that Confluence instance.
But with GitHub, most people actually comfortable with Git and Pull requests will most definitely have a GitHub account already, therefore lowering the hurdle of entry to start contributing.

**Comment by Wild1145** [comment]
> > Equally though "Anonymous" edits aren't possible using anything over Git either (And fwiw it is possible on Confluence, it's just bad practice) as you have to have a Github account and things have to be attributable to that account, no different to Confluence.
> 
> My point with "Anonymous" edits was that a Confluence SaaS instance uses its own user database, so someone wanting to contribute to the documentation would have to create a specific account, just for that Confluence instance. But with GitHub, most people actually comfortable with Git and Pull requests, will most definitely have a GitHub account already, therefore lowering the hurdle of entry to start contributing.

Ahh sorry I see what you mean. Yes having a single account makes things easier, and in that way the barrier to entry is lower, though I'd argue the technical complexity of a Git based solution makes the bar of entry to make meaningful contributions significantly higher using a git based / similar solution compared to a WYSIWYG / more visual tool which Confluence (And others) supports. Being able to visualise your edits and not have to understand the depth and complexity of a documentation tool driven from code.

**Comment by John-S4** [comment]
@Wild1145 I see your point about the complexity of making edits - the one thing that all of the Git based solutions (that I know of) are lacking is a WYSIWYG editor, and markdown is a pain if you have never used it. 

Having said that, unless something amazing occurs to me magically during the morning, I'm going to implement Docusaurus, it has a link on each doc page to 'edit' that will take people to GH to do that which is pretty easy, and I'll write a page explaining basic markdown just in case anyone doesn't know it.

**Comment by John-S4** [comment]
Docusauras is now set up, we haven't managed to create any docs yet, but now there is at least a place to put them when we do.
